### PR TITLE
add user agent,clean the code add main function to make the code easi…

### PR DESCRIPTION
**Pull request by Al13n0**
Fix issue #6
 
 I created this pull request to fix your code didn't work because the **User Agent** was missing in the requests.
 I have also update the file inside the Havoc folder with the latest one that i found here:
 https://github.com/HavocFramework/havoc-py/tree/main/havoc
 
I also cleaned the code, adding a Main functions this make the code easier to read.
 I tested the code and it works on both version of Havoc 0.5 and 0.6

### CODE REVIEW

**Comment by Cyb3rC3lt** [comment]
Just to add this fixes the current issue but the url also needs updating to wss so it looks like this:

wss://localhost:40056/service-endpoint

Edit: Actually registering the agent still struggles if you have any hints on that?

**Comment by CodeXTF2** [comment]
hmm what error do you get when registering the agent?

**Comment by Cyb3rC3lt** [comment]
image

**Comment by Cyb3rC3lt** [comment]
Just to add context I have Havoc running on 127.0.0.1 and a listener on port 80. My agent url is set to url = 'http://127.0.0.1'

image

**Comment by Cyb3rC3lt** [comment]
Weirdly putting in the IP address rather than localhost helped, but it still crashed at this point. I am using the Dev branch and the havoc python folder from Revenant which is meant to have some fixes for 3rd parties in it.

image

image

**Comment by CodeXTF2** [comment]
not too sure i havent touched the havoc api in literal ages il have to check on this next holiday if im free if its still an issue. Could the custom agent spec have changed? Maybe try it on an old version of havoc to test if it works. if it does that would indicate some sort of a spec change ig

**Comment by CodeXTF2** [comment]
looks ok. gonna merge it and fix the bugs now.

**Pull request merged**
